<link rel="stylesheet" href="css/photograph.css">
    <header>
        <ul id="title">
            <li id="pmg"><label for="site-prefeitura"><img src="/img/pmg/logo.png"></img></label></li>
            <li id="coor"><h1>Coordenação de Tecnologia da Informação</h1></li>
        </ul>
        <nav id="menu-base">
            <ul>
                <li id="site-prefeitura" onclick="goPref()">Home</li>
                <li id="selecionado">Fotografias</li>
            </ul>
        </nav>
    </header>

    <section id="main">
        <div id="imagem">
            <video id="camera"></video>
            <canvas id="imagem-capturada" style="display:none;"></canvas>
        </div>
        <div id="infos">
            <div><h2>Informações</h2></div>
            <h3>ID:&nbsp;<?=$_POST['id_photo']?></h3>
            <h3>Nome:&nbsp;<input type="text" size="25" id="nome_photo" name="nome_photo" value="<?=$_POST['nome_photo']?>"></h3>
            <h3>Descrição:</h3><textarea name="desc_photo" id="desc_photo" rows="7" cols="32"><?=$_POST['desc_photo']?></textarea>
            <input type="hidden" id='link_photo' name="link_photo" value="">
            <input onclick="reloadPage()" class="btn btn-warning" type="button" id='tn' value="Tentar Novamente">
            <input onclick="sendToPHP()" class="btn btn-success" type="button" id='send' value="Enviar" >
        </div>
        <div id="botao-capturar">
            <input type="button" value="Capturar" onclick="photograph()" id="capture" class="btn btn-success">
        </div>
    </section>
    <footer>
        <h3>Prefeitura Municipal de Gravatá</h3>
    </footer>
    <script src="/js/photograph.js"></script>
    <script>
        function sendToPHP(){
            let nome = document.querySelector('#nome_photo');
            let valorNome = nome.value;

            if(<?=$_POST['id_photo']?> == 1){
                if(valorNome == 'user'){
                    valorNome = <?=$_POST['id_resident_photo']?> + ".png";
                } else {
                    valorNome += '.png';
                }
                nome.value = valorNome;
            }

            let desc = document.querySelector('#desc_photo');

            let link = document.querySelector('#link_photo');

            link.value = `/img/residents_photos/`;

            const canvasImg = document.querySelector('#imagem-capturada');

            let http = new XMLHttpRequest();

            let imagem = canvasImg.toDataURL();

            let params = {
                "name_foto": nome.value,
                "descricao": desc.value,
                "link_foto": link.value,
                "image": imagem
            }

            http.open("POST", "/register_photograph", true);
            http.setRequestHeader("Content-type", "application/json");
            http.onreadystatechange = function() {
                if(http.readyState == 4 && http.status == 200) {
                    alert("Imagem salva com sucesso");
                }
            }

            http.send(JSON.stringify(params));//ERRO 500, descobrir o q é e concertar o CSS

            //daqui pra cima, vai para o servidor

            location.href = '/residents'

        }

        function goPref(){
            location.href = "https://gravata.pe.gov.br/";
        }
    </script>