<div class="nav navbar align-items-center justify-content-between bg-dark" style="height:4rem">
    <h4 class="m-0 text-light">Editar cadastro</h4>
    <h4 class="m-0 text-white"><i class="fas fa-dolly mr-2" style="font-size:28px"></i></h4>
</div>
<div class="d-flex align-items-center justify-content-center px-1" style="min-height: 91vh">
    <div class="py-4 px-3 card" style="width:30rem">
        <form action="/update_order" method="post">
            <input type="hidden" name="id_encomenda" value="<?=$_POST['id_encomenda']?>">
            <div class="label-float mt-4">    
                <input type="text" name="empresa" class="form-custom form-control mt-1 bg-transparent" size="60" maxlength="60" placeholder="empresa" value="<?=$_POST['empresa']?>">
                <label>Empresa</label>
            </div>
            <div class="label-float mt-4">    
                <input type="text" name="apartamento" class="form-custom form-control mt-1 bg-transparent" size="60" maxlength="20" placeholder="Apartamento" value="<?=$_POST['apartamento']?>">
                <label>Setor</label>
            </div>
            <div class="label-float mt-4">
            <input type="text" name="bloco" class="form-custom form-control mt-1 bg-transparent" size="60" maxlength="100" placeholder="Destinatário" value="<?=$_POST['bloco']?>">
                <label>Destinatário</label>
            </div>
            <button type="submit" class="btn btn-register text-white w-100 mt-5">Atualizar</button>   
            <a href="/orders" class="btn btn-danger text-white w-100 mt-2">Voltar</a>      
        </form>
    </div>
</div>